### PR TITLE
Cosipy intro

### PR DESCRIPTION
**Pull request by israelmcmc**
All the info I want to write is there already. No gramma check yet though...

### CODE REVIEW

**Comment by ckarwin** [comment]
@israelmcmc This is excellent! I plan to go through this week and provide detailed feedback. I already started collecting my comments. In the meantime, I think we should get this merged before Monday's science meeting. What do you think, are you comfortable with merging it now, and then updating things this week as needed?

**Comment by ckarwin** [comment]
Here are some small changes I have so far, which should be fast to fix: 

1) The cosipy product are ... --> The cosipy products are ...

Looking at the cosipy documentation page (https://cositools.github.io/cosipy/):

2) Same typo as mentioned above. 

3) Contributing section: 

> Cosipy is open-source and anyone can contribute. The cosipy library is open-source and anyone can contribute!

This is repeated twice. 

4) The prefered communication channel the GitHub repository --> The preferred communication channel is the GitHub repository: 

Back to DC2 cosipy intro

5) shown in the following diagram as the "High-level Data Abalysis" block. --> shown in the following diagram as the "High-level Data Analysis" block.

6) I am confused by the numbering used in the diagram. The published version of the paper has levels 0, 1, 2, 3, and 4. I think the specifications of the levels in the diagram that you're using are less clear. Is there a reason why this has changed? 

7) This means that different source hypothesis are convolved... --> This means that different source hypotheses are convolved...

8) and therefore find the best. --> and therefore find the best model.

9) 

> In our case, the physical sky model is composed by all the source parameters that we want to fit.

Maybe consider rephrasing this, because it's a bit misleading. The physical sky model is made up of all the sources, even if none of the source parameters are being fit. They still contribute to the total counts. 

10) The observed data corresponds to the measured counts on each bin. --> The observed data corresponds to the measured counts in each bin.

11) In COSI we bin the data on measured energy,  --> In COSI we bin the data in measured energy,

**Comment by israelmcmc** [comment]
Thanks, @ckarwin! Yeah, let's merge it before the meeting today. Let me just address your comments and give it one more proofreading pass

**Comment by israelmcmc** [comment]
@ckarwin I think fixed the most obvious typos. We can continue iterate on this, but I think it's good enough to merge already. Please go ahead and merge this and the one in [cosipy](https://github.com/cositools/cosipy/pull/126) whenever you want.

**Pull request merged**
